services:
  cadvisor_ws:
    build: .
    image: 'gcr.io/cadvisor/cadvisor:v0.49.1'
    container_name: 'c_cadvisor_ws'
    ports:
      - 8091:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true